# Edit this file to set the Messenger's module settings programmatically instead of using the GUI
# This is regular YAML syntax. See http://docs.ansible.com/ansible/YAMLSyntax.html
# You can override these settings with ENV variables. They are commented below.

# hostname: "https://34f0ca2c.ngrok.io/api/botpress-messenger/webhook" # MESSENGER_HOST
hostname: "34f0ca2c.ngrok.io" # MESSENGER_HOST

applicationID: "170707896989662" # MESSENGER_APP_ID
accessToken: "EAACbQgePd94BAMoBZCLvLWVTdAE9aw29e4oDis6Uya8ht8RIom8E2amJGP3mhVL6shpvhQTgUHXMk2pnJZCxL21ZCbPGR21LZBTuONvqwFTfXh8di4nT37e7vTp5subfJ759zbCZCtHpOuOyNNO0LNYkzZBwWmH5uHIE7Ur6l2N2ZBQae7eDK6w" # MESSENGER_ACCESS_TOKEN
appSecret: "3cb4295fbf9a981e9a5c3530fe60a6ce" # MESSENGER_APP_SECRET

verifyToken: "12345678" # MESSENGER_VERIFY_TOKEN

# displayGetStarted: true
# greetingMessage: ""

# https://developers.facebook.com/docs/messenger-platform/messenger-profile/persistent-menu
# persistentMenuItems: []

# targetAudience: openToAll
# targetAudienceOpenToSome: ""
# targetAudienceCloseToSome: ""

# trustedDomains: []
# autoRespondGetStarted: true

# paymentTesters: []

# chatExtensionHomeUrl: ""
# chatExtensionInTest: true
# chatExtensionShowShareButton: false

enabled: true
